AzureAd Login Sample/Controllers/TransferRequestController.cs
using Newtonsoft.Json;
using POC.Controllers;
using POC.DataAccess;
using POC.DataAccess.Model;
using POC.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AzureAd_Login_Sample.Controllers
{
    public class TransferRequestController : BaseController
    {
        // GET: TransferRequest
        public ActionResult Index(TransferRequestViewModel model, string Filterby = "ALL", string Status = "ALL", string Type = "ALL")
        {
            if (Request.Cookies["UserToken"] != null)
            {
                ViewBag.Name = Request.Cookies["UserName"]?.Value;
                ViewBag.UserGuid = Request.Cookies["UserGuid"]?.Value;
                // The 'preferred_username' claim can be used for showing the username
                ViewBag.Username = Request.Cookies["UserEmail"]?.Value;
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            //var AllTransferRequest = WebHelper.GetWebAPIResponseWithErrorDetails(GetAllTransferRequestAPIURL, WebHelper.ContentType.application_json, WebRequestMethods.Http.Get, "", "", "", "", BearerToken);
            //var AllTransferresponse = JsonConvert.DeserializeObject<List<AllTransferRequestResponse>>(AllTransferRequest.ResponseString);
            var AllTransferresponse = GetDataFromCache<List<AllTransferRequestResponse>>("AllTransferResponse", GetAllTransferRequestAPIURL);
            if (AllTransferresponse != null)
            {
                model.lst = new List<TransferRequests>();
                if (Filterby != "All")
                {
                    if (Filterby == "Day")
                    {
                        AllTransferresponse = AllTransferresponse.Where(p => p.createdAt >= DateTime.Now.Date.AddHours(-24)).ToList();
                    }
                    if (Filterby == "Week")
                    {
                        AllTransferresponse = AllTransferresponse.Where(p => p.createdAt >= DateTime.Now.Date.AddDays(-7)).ToList();
                    }
                    if (Filterby == "Month")
                    {
                        AllTransferresponse = AllTransferresponse.Where(p => p.createdAt >= DateTime.Now.Date.AddMonths(-1)).ToList();
                    }
                }

                var _Status = AllTransferresponse.Select(p => p.status).Distinct().ToList();
                ViewBag.StatusList = PopulateDropdownListValues(_Status, Status);
                var _Type = AllTransferresponse.Select(p => p.type).Distinct().ToList();
                ViewBag.TypeList = PopulateDropdownListValues(_Type, Type);
                if (Status.ToUpper() != "ALL")
                {
                    AllTransferresponse = AllTransferresponse.Where(p => p.status == Status).ToList();
                }
                if (Type.ToUpper() != "ALL")
                {
                    AllTransferresponse = AllTransferresponse.Where(p => p.type == Type).ToList();
                }
                //get all generated VC List
                DashboardService ds = new DashboardService();
                var LstVc = ds.PieceInfos.Where(p => p.VCId != null).Distinct().ToList();

                foreach (var transfer in AllTransferresponse)
                {
                    var productweight = transfer.product.productVC.credentialSubject.product.weight;
                    TransferRequests obj = new TransferRequests();
                    obj.RequestId = transfer.id;
                    obj.Updated = transfer.updatedAt;
                    obj.Type = transfer.type;
                    obj.CreatedBy = "Steel Co.";
                    obj.ProductType = "Stainless Steel Products";
                    obj.Quantity = productweight == null ? "" : (productweight.value + " " + productweight.unitCode);
                    obj.Status = transfer.status;
                    obj.ProductId = transfer.product.id;
                    obj.Coil = LstVc?.Where(p => p.VCId == transfer.product.id).FirstOrDefault()?.MES_PCE_IDENT_NO.ToString();
                    obj.SerialNumber = LstVc?.Where(p => p.VCId == transfer.product.id).FirstOrDefault()?.PCE_DISPLAY_NO.ToString();
                    obj.LiftNumber = LstVc?.Where(p => p.VCId == transfer.product.id).FirstOrDefault()?.LIFT_NO.ToString();
                    model.lst.Add(obj);
                }
                ViewBag.Filterby = Filterby;
                ViewBag.Status = Status;
                ViewBag.Type = Type;
            }

            return View(model);
        }
        public List<SelectListItem> PopulateDropdownListValues(List<string> lst, string SelectedValue)
        {
            string SelectText = "ALL";
            List<SelectListItem> result = (from p in lst.AsEnumerable()
                                           select new SelectListItem
                                           {
                                               Text = p.Trim(),
                                               Value = p.Trim()
                                           }).ToList();
            result.Insert(0, new SelectListItem
            {
                Text = SelectText,
                Value = SelectText
            });
            if (!string.IsNullOrEmpty(SelectedValue))
            {
                result.Find(c => c.Value == SelectedValue).Selected = true;
            }
            return result;
        }
    }
}

AzureAd Login Sample/Views/TransferRequest/Index.cshtml
@model POC.DataAccess.Model.TransferRequestViewModel
@{
    ViewBag.Title = "Transfer Request Status";
    ViewBag.Page = "transferrequests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #tblTransferRequests_filter.dataTables_filter label {
        width: 100%;
    }

    .swal2-confirm {
        margin-left: 20px !important;
    }

    #tblTransferRequests tbody > tr:hover {
        background-color: #ff6f47;
    }

        #tblTransferRequests tbody > tr:hover > td > i {
            background-color: #fff;
        }

    .table-striped > tbody > tr:nth-child(even):hover {
        background-color: #ff6f47 !important;
    }

    .table-striped > tbody > tr:nth-child(even) {
        opacity: unset;
        background-color: #F8DFB6 !important;
    }
    .dataTables_wrapper .dataTables_paginate .ellipsis {
        display: none;
    }
    table.dataTable tbody th, table.dataTable tbody td {
        padding: 4px 6px !important;
    }

    .dt-buttons {
        text-align: right;
        margin-bottom: 10px;
    }

    .customheightselect {
        height: 30px;
    }

    #tblTransferRequests_filter label {
        visibility: hidden
    }

        #tblTransferRequests_filter label input {
            visibility: visible
        }
    .form-group {
        border-bottom:none !important;
        padding-bottom:0px !important;
        margin-bottom:0px !important;
    }
    .dt-buttons {
        display:none;
    }
    .dataTables_filter {
        margin-top:-20px;
    }
    .dt-buttons1 {
        text-align: right;
        padding-right: 0px;
    }
</style>
@using (Html.BeginForm("Index", "TransferRequest", FormMethod.Post, new { @class = "form-horizontal form-bordered", enctype = "multipart/form-data", onsubmit = "showLoader(this);", @novalidate = "novalidate" }))
{
    <div class="col-md-12" style="margin-top:10px;"></div>
    <div class="col-md-12">
        <div class="col-md-10" style="padding-left: 0px;">
            <input type="button" class="btn btn-black applydatefilter" id="ALL" value="All" />
            <input type="button" class="btn btn-black applydatefilter" id="Day" value="Day" />
            <input type="button" class="btn btn-black applydatefilter" id="Week" value="Week" />
            <input type="button" class="btn btn-black applydatefilter" id="Month" value="Month" />
        </div>
        <div class="dt-buttons1 col-md-2"> 
        <button class="buttons-html5 btn btn-orange" id="exporttocsvTransferRequest" tabindex="0" aria-controls="tblTransferRequests" type="button"><span>CSV</span></button> <button id="exporttoexcelTransferRequest" class="buttons-html5 btn btn-orange" tabindex="0" aria-controls="tblTransferRequests" type="button"><span>Excel</span></button> </div>
        <div class="form-inline col-md-12" style="padding-top:5px;">
            <div class="form-group col-md-4" style="padding-left:0px;margin-left:-30px;">
                <label class="col-sm-2 col-form-label">Status:</label>
                <div class="col-md-10">
                    @Html.DropDownList("ddlStatus", (List<SelectListItem>)
    ViewBag.StatusList,
    htmlAttributes: new { @class = "form-control", @style = "width:100%;" })
                </div>
            </div>

            <div class="form-group col-md-4">
                <label class="col-sm-2 col-form-label">Type:</label>
                <div class="col-md-10">
                    @Html.DropDownList("ddlType", (List<SelectListItem>)
 ViewBag.TypeList,
 htmlAttributes: new { @class = "form-control", @style = "width:100%;" })
                </div>
            </div>
            <button type="button" class="btn btn-orange applyfilter">Apply Filter</button>
        </div>
    </div>
    <div class="col-md-12" style="margin-top:10px;"></div>
    <div class="col-md-12">
        @if (Model.lst != null)
        {
            <table class="table table-bordered table-striped table-hover js-basic-example dataTable" id="tblTransferRequests">
                <thead>
                    <tr>
                        <th scope="col">Request Id</th>
                        <th scope="col">Product Id</th>
                        <th scope="col">Updated</th>
                        <th scope="col">Type</th>
                        <th scope="col">Created by</th>
                        <th scope="col">Product type</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Status</th>
                        <th scope="col">PCE</th>
                        <th scope="col">Serial Number</th>
                        <th scope="col">Lift Number</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.lst)
                    {
                    <tr>
                        <td>@item.RequestId</td>
                        <td>@item.ProductId</td>
                        <td>@item.Updated.ToString("MMM dd,yyyy")</td>
                        <td>@item.Type</td>
                        <td>@item.CreatedBy</td>
                        <td>@item.ProductType</td>
                        <td>@item.Quantity</td>
                        <td>@item.Status</td>
                        <td>@item.Coil</td>
                        <td>@item.SerialNumber</td>
                        <td>@item.LiftNumber</td>
                    </tr>
                    }
                </tbody>
            </table>
        }
    </div>
    <input type="hidden" id="hdnFilterBy" name="hdnFilterBy" value="@ViewBag.Filterby" />
}
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            //var input = $('#tblTransferRequests_filter label input');
            //$("#tblTransferRequests_filter label").html('');
            //$("#tblTransferRequests_filter label").append(input);
            $("select", "#tblTransferRequests_length").addClass('customheightselect');
            $("button", ".dt-buttons").addClass('btn btn-orange');
            //$("#tblContract_length").addClass('col-md-6');
            var filterbyval = $('#hdnFilterBy').val();
            $('#' + filterbyval).removeClass('btn-black');
            $('#' + filterbyval).addClass('btn-orange');
        });

        $('.applyfilter').click(function () {
            var filterby = $('#hdnFilterBy').val();
            var status = $('#ddlStatus').val();
            var type = $('#ddlType').val();
            var url = '@Url.Action("Index", "TransferRequest")?Filterby=' + filterby + '&Status=' + status + '&Type=' + type;
            location.href = url;

        });
        $('.applydatefilter').click(function () {
            var filterbyval = $(this).attr('id');
            $('#hdnFilterBy').val(filterbyval);
            $(".applydatefilter").removeClass('btn-orange');
            $(".applydatefilter").addClass('btn-black');
            $('#' + filterbyval).addClass('btn-orange');
            $('#' + filterbyval).removeClass('btn-black');
        });

    </script>
}