AzureAd Login Sample/Controllers/ClaimsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POC.Controllers
{
    [Authorize]
    public class ClaimsController : Controller
    {
        /// <summary>
        /// Add user's claims to viewbag
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var userClaims = User.Identity as System.Security.Claims.ClaimsIdentity;

            //You get the user's first and last name below:
            ViewBag.Name = userClaims?.FindFirst("name")?.Value;

            // The 'preferred_username' claim can be used for showing the username
            ViewBag.Username = userClaims?.FindFirst("preferred_username")?.Value;

            // The subject/ NameIdentifier claim can be used to uniquely identify the user across the web
            ViewBag.Subject = userClaims?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            // TenantId is the unique Tenant Id - which represents an organization in Azure AD
            ViewBag.TenantId = userClaims?.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid")?.Value;

            return View();
        }
    }
}

AzureAd Login Sample/Controllers/ReportController.cs
using Newtonsoft.Json;
using POC.Controllers;
using POC.DataAccess;
using POC.DataAccess.Model;
using POC.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;

namespace AzureAd_Login_Sample.Controllers
{
    public class ReportController : BaseController
    {
        public string GetAllProductAPIURL { get; set; } = string.Empty;
        public ReportController()
        {
            GetAllProductAPIURL = ApiDomain + "/v1/products?category=active&offset=0&count=100";
        }
        // GET: Report
        public ActionResult Index(ReportView model)
        {
            if (Request.Cookies["UserToken"] != null)
            {
                ViewBag.Name = Request.Cookies["UserName"]?.Value;
                ViewBag.UserGuid = Request.Cookies["UserGuid"]?.Value;
                // The 'preferred_username' claim can be used for showing the username
                ViewBag.Username = Request.Cookies["UserEmail"]?.Value;
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            //TempData["Message"] = "test";
            ViewBag.Page = "report";

            //string GetAllProductAPIURL = "https://www.mockachino.com/97fd072e-cfdf-45/v1/products?category=active&offset=0&count=100";
            //string GetAllProductAPIURL = ApiDomain + "/v1/products?category=active&offset=0&count=100";
            //var Allproductrequest = WebHelper.GetWebAPIResponseWithErrorDetails(GetAllProductAPIURL, WebHelper.ContentType.application_json, WebRequestMethods.Http.Get, "", "", "", "", BearerToken);
            //var Allproductresponse = JsonConvert.DeserializeObject<AllProductResponse>(Allproductrequest.ResponseString);
            var Allproductresponse = GetDataFromCache<AllProductResponse>("AllProductResponse", GetAllProductAPIURL);
            if (Allproductresponse != null)
            {
                model.Active = (int)Allproductresponse.totalProductsCount?.active;
                model.Consumed = (int)Allproductresponse.totalProductsCount?.consumed;
                model.History = (int)Allproductresponse.totalProductsCount?.history;
                model.SharedWithme = (int)Allproductresponse.totalProductsCount?.sharedWithMe;

                ViewBag.Active = model.Active;
                ViewBag.Consumed = model.Consumed;
                // ViewBag.History = model.History;
                ViewBag.SharedWithme = model.SharedWithme;
                List<Event> lstEvents = new List<Event>();
                if (Allproductresponse.products.active != null)
                {
                    foreach (var activeprod in Allproductresponse.products.active)
                    {
                        if (activeprod.events != null)
                        {
                            foreach (var objevent in activeprod.events)
                            {
                                lstEvents.Add(objevent);
                            }
                        }
                    }
                }

                TempData["Events"] = lstEvents;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult GetTimeLineData(string Filterdays = "3")
        {
            int days = Convert.ToInt32(Filterdays);
            List<object> iData = new List<object>();
            List<string> labels = new List<string>();
            List<int> data = new List<int>();
            List<Event> lstEvents = new List<Event>();

            List<AllPRoductEventsLineGraph> AllProductEvents = new List<AllPRoductEventsLineGraph>();
            DateTime EndDate = DateTime.Now, StartDate = DateTime.Now;
            if (days > 0)
            {
                if (days == 3)
                {
                    StartDate = EndDate.AddDays(-3);
                }
                else if (days == 7)
                {
                    StartDate = EndDate.AddDays(-7);
                }
                else if (days == 30)
                {
                    StartDate = EndDate.AddMonths(-1);
                }
                else if (days == 90)
                {
                    StartDate = EndDate.AddMonths(-3);
                }
            }

            if (TempData["Events"] == null)
            {
                //string GetAllProductAPIURL = "https://www.mockachino.com/97fd072e-cfdf-45/v1/products?category=active&offset=0&count=100";
                //var Allproductrequest = WebHelper.GetWebAPIResponseWithErrorDetails(GetAllProductAPIURL, WebHelper.ContentType.application_json, WebRequestMethods.Http.Get, "", "", "", "", BearerToken);
                //var Allproductresponse = JsonConvert.DeserializeObject<AllProductResponse>(Allproductrequest.ResponseString);
                var Allproductresponse = GetDataFromCache<AllProductResponse>("AllProductResponse", GetAllProductAPIURL);
                if (Allproductresponse.products.active != null)
                {
                    foreach (var activeprod in Allproductresponse.products.active)
                    {
                        if (activeprod.events != null)
                        {
                            foreach (var objevent in activeprod.events)
                            {
                                lstEvents.Add(objevent);
                            }
                        }
                    }
                }
            }
            else
            {
                lstEvents = (List<Event>)TempData["Events"];
            }
            if (lstEvents.Count > 0)
            {
                foreach (var objevent in lstEvents)
                {
                    AllProductEvents.Add(new AllPRoductEventsLineGraph { Count = 1, Status = objevent.eventType, FilterDate = objevent.eventVC.issuanceDate.Date, IssuedDate = objevent.eventVC.issuanceDate, CreatedDate = objevent.eventVC.issuanceDate.ToString("yyyy-MM-dd") });
                }
                if (AllProductEvents.Count > 0)
                {
                    //ViewBag.TransportStartCount = AllProductEvents.Where(p => p.Status == "Create").ToList();
                    AllProductEvents = AllProductEvents.Where(c => c.FilterDate >= StartDate.Date && c.FilterDate <= EndDate.Date).ToList();
                    labels = AllProductEvents.OrderBy(c => c.IssuedDate).Select(p => p.CreatedDate).Distinct().ToList();
                    iData.Add(labels);
                    foreach (var datestr in labels)
                    {
                        data.Add(AllProductEvents.Where(p => p.CreatedDate == datestr).Sum(p => p.Count));
                    }
                    iData.Add(data);
                }
            }

            //labels.Add("2021-11-05");
            //labels.Add("2021-11-06");
            //labels.Add("2021-11-07");
            //iData.Add(labels);

            //data.Add(1);
            //data.Add(2);
            //data.Add(3);
            //iData.Add(data);
            string jsonGraphdata = JsonConvert.SerializeObject(iData);
            return new JsonResult { Data = new { data = jsonGraphdata } };
        }
        [HttpPost]
        public ActionResult GetBarGraphData(string Filterdays = "3")
        {
            int days = Convert.ToInt32(Filterdays == "" ? "3" : Filterdays);
            List<object> iData = new List<object>();
            List<string> labels = new List<string>();
            List<int> data = new List<int>();
            List<Event> lstEvents = new List<Event>();
            List<Active> lstActiveProducts = new List<Active>();
            List<AllProductBarGraph> AllProductBarGraphdata = new List<AllProductBarGraph>();
            DateTime EndDate = DateTime.Now, StartDate = DateTime.Now;
            if (days > 0)
            {
                if (days == 3)
                {
                    StartDate = EndDate.AddDays(-3);
                    for (int i = 0; i < 3; i++)
                    {
                        labels.Add(StartDate.AddDays(i).Date.ToString("yyyy-MM-dd"));
                    }
                }
                else if (days == 7)
                {
                    StartDate = EndDate.AddDays(-7);
                    for (int i = 0; i < 7; i++)
                    {
                        labels.Add(StartDate.AddDays(i).Date.ToString("yyyy-MM-dd"));
                    }
                }
                else if (days == 30)
                {
                    StartDate = EndDate.AddMonths(-1);
                    for (int i = 0; i < DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month); i++)
                    {
                        labels.Add(StartDate.AddDays(i).Date.ToString("yyyy-MM-dd"));
                    }
                }
                else if (days == 90)
                {
                    StartDate = EndDate.AddMonths(-3);
                    for (int i = 0; i < 3; i++)
                    {
                        labels.Add(StartDate.AddMonths(i).Date.ToString("MMM"));
                    }
                }
            }
            iData.Add(labels);
            if (TempData["AllProducts"] != null)
            {
                lstActiveProducts = (List<Active>)TempData["AllProducts"];
            }
            else
            {
                //var Allproductrequest = WebHelper.GetWebAPIResponseWithErrorDetails(GetAllProductAPIURL, WebHelper.ContentType.application_json, WebRequestMethods.Http.Get, "", "", "", "", BearerToken);
                //var Allproductresponse = JsonConvert.DeserializeObject<AllProductResponse>(Allproductrequest.ResponseString);
                var Allproductresponse = GetDataFromCache<AllProductResponse>("AllProductResponse", GetAllProductAPIURL);
                if (Allproductresponse != null)
                {
                    lstActiveProducts = Allproductresponse.products?.active;

AzureAd Login Sample/Views/Home/Index.cshtml
@{
    Layout = null;
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AMD MetalTrail</title>
    <!-- Web Fonts  -->
    <link href="~/Theme/Css/Googlefonts.css" rel="stylesheet" />

    <!-- Vendor CSS -->
    <link href="~/Theme/Css/bootstrap.css" rel="stylesheet" />
    <link href="~/Theme/Css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Theme/Css/magnific-popup.css" rel="stylesheet" />

    <!-- Theme CSS -->
    <link href="~/Theme/Css/theme.css" rel="stylesheet" />

    <!-- Skin CSS -->
    <link href="~/Theme/Css/default.css" rel="stylesheet" />

    <!-- Theme Custom CSS -->
    <link href="~/Theme/Css/theme-custom.css" rel="stylesheet" />
</head>
<body>
    <section class="body-sign">
        <div class="center-sign">
            <a href="/" class="logo pull-left">
                <img src="~/Theme/Images/logo.png" height="54" alt="IQ Lance" />
            </a>

            <div class="panel panel-sign">
                <div class="panel-title-sign mt-xl text-right">
                    <h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i>Sign In</h2>
                </div>
                <div class="panel-body" style="display:none;">
                    @if (!Request.IsAuthenticated)
                    {
                        <!-- If the user is not authenticated, display the sign-in button -->
                        <a href="@Url.Action("SignIn", "Home")" style="text-decoration: none;">
                            <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="300px" height="50px" viewBox="0 0 3278 522" class="SignInButton">
                            <style type="text/css">
                                .fil0:hover {
                                    fill: #4B4B4B;
                                }

                                .fnt0 {
                                    font-size: 260px;
                                    font-family: 'Segoe UI Semibold', 'Segoe UI';
                                    text-decoration: none;
                                }
</style>
                            <rect class="fil0" x="2" y="2" width="3174" height="517" fill="black" />
                            <rect x="150" y="129" width="122" height="122" fill="#F35325" />
                            <rect x="284" y="129" width="122" height="122" fill="#81BC06" />
                            <rect x="150" y="263" width="122" height="122" fill="#05A6F0" />
                            <rect x="284" y="263" width="122" height="122" fill="#FFBA08" />
                            <text x="470" y="357" fill="white" class="fnt0">Sign in with Microsoft</text>
        </svg>
                        </a>
                    }
                    else
                    {
                        <span><br />Hello @System.Security.Claims.ClaimsPrincipal.Current.FindFirst("name").Value;</span>
                        <br /><br />
                        @Html.ActionLink("See Your Claims", "Index", "Claims")
                        <br /><br />
                        @Html.ActionLink("Sign out", "SignOut", "Home")
                    }
                    @if (!string.IsNullOrWhiteSpace(Request.QueryString["errormessage"]))
                    {
                        <div style="background-color:red;color:white;font-weight: bold;">Error: @Request.QueryString["errormessage"]</div>
                    }
                </div>
            </div>
            <p class="text-center text-muted mt-md mb-md">&copy; Copyright @DateTime.Now.Year.ToString(). All rights reserved.</p>
        </div>
    </section>
</body>
</html>

AzureAd Login Sample/Views/Home/Test.cshtml
@model POC.DataAccess.Model.ProductDetailView
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Theme/Scripts/highchart.js"></script>
<script src="~/Theme/Scripts/highcharts-3d.js"></script>
<div class="col-md-12" id="barcontainer" style="height: 400px;">
</div>
@section scripts{
    <script language="JavaScript">
      
        $(document).ready(function () {

            // Redner chart
            const chart = Highcharts.chart('barcontainer', {
                series: [{
                    data: [],
                    type: 'column'
                }]
            });

            //alert(document.readyState);
           
            CallBarGraph();


        });

         function CallBarGraph() {

            var filterdays = "";
            if ($("#Model_DateFilterBarGraph").val() == "Last 3 Days") { filterdays = "3"; }
            else if ($("#Model_DateFilterBarGraph").val() == "Last 7 Days") { filterdays = "7"; }
            else if ($("#Model_DateFilterBarGraph").val() == "Last 1 Month") { filterdays = "30"; }
            else if ($("#Model_DateFilterBarGraph").val() == "Last 3 Months") { filterdays = "90"; }
              $.ajax({
                  type: "POST",
                  cache: false,
            url: '@Url.Action("GetBarGraphData", "Report")',
            data: { Filterdays: filterdays},
            success: function (chData) {
                //alert(chData.data);
                var xAxisData = JSON.parse(chData.categories);
                var ProductVcCountData = JSON.parse(chData.ProductVCIssuesCount);
                var TransportStartCountData = JSON.parse(chData.TransportStartEventCount);
                console.log(xAxisData);
                console.log(ProductVcCountData);
                //For Bar Chart
                var t =Highcharts.chart('barcontainer', {
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: 'Product VC Created vs In Transportation'
                    },
                    //subtitle: {
                    //    text: 'Source: WorldClimate.com'
                    //},
                    xAxis: {
                        categories: xAxisData,
                        crosshair: true
                    },
                    yAxis: {
                        min: 0
                    },
                    tooltip: {
                        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                            '<td style="padding:0"><b>{point.y}</b></td></tr>',
                        footerFormat: '</table>',
                        shared: true,
                        useHTML: true
                    },
                    rangeSelector: {
                        enabled: true
                    },
                    plotOptions: {
                        column: {
                            pointPadding: 0.2,
                            borderWidth: 0
                        }
                    },
                    series: [{
                        name: 'VC Created',
                        data: ProductVcCountData

                    },
                        {
                        name: 'In Trasport',
                            data: TransportStartCountData

                    }]
                });
                if (t.series.data != undefined) {
                    //if (chart.data.empty == 'true') {
                    alert(t.series.data);
                    

                    //    chart.destroy(); //why remove all series, while you can remove chart to free some space and resources

                    //    $('#barcontainer').html("<div class='empty-chart'>No data available for selected date range</div>"); //now show some information about chart
                }

                  },
                   
              });
            


        }
    </script>
}

AzureAd Login Sample/Views/Home/_ProductDetail.cshtml
@model  List<POC.DataAccess.Model.ProductDetail>
@if (Model.Count > 0)
{
    <div>
        <table class="table table-condensed table-bordered" id="tblProductDetail">
            <caption>Observation Details</caption>
            <thead>
                <tr>
                    <th>Observation Name</th>
                    <th>Measured Unit</th>
                    <th>Measured Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ObservationDescription</td>
                        <td>@item.Unit</td>
                        <td>@item.Value</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
   <div style="text-align: center; color: red; font-weight: bold;">
       No Records Found for this Product
   </div>
}